### ISSUE TITLE
typo in handlebars template?

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-close#1]
one of the assigned classes is `naviation-core-item`, should this not be `navigation-core-item`?

**Comment by tomgreenfield** [comment]
Pained me to do it but it was to match the typo in our [theme](https://github.com/cgkineo/adapt-kineo-theme/blob/master/templates/navigation.hbs) and subsequent typo in [base.less](https://dev.kineo.com/trac/adapt/browser/trunk/v1.2%20scorm%20test/src/core/less/base.less#L127) in our v1.2 framework. This class can probably be ditched if we don't need legacy support.

**Comment by moloko** [comment]
Aha I did wonder if that might be it! Cheers for confirming.
