### ISSUE TITLE
close button gets added to the start of the navigation bar

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-close#11]
Typically it's generally displayed as the last item in the navbar - so by prepending it to the `.navigation-inner` div (current behaviour), the tab order won't match the display order.

Until the Adapt FW adds a proper method for ordering buttons in the navigation bar, it's probably best to change the code that adds the close button so that it appends it.

**Comment by kirsty-hames** [comment]
This would get resolved by #14
