### ISSUE TITLE
Problem with progress reporting on close and Chrome version > 80

### ISSUE THREAD

**Issue by dymitar** [cgkineo/adapt-close#15]
Because Chrome disallows synchronous XHR the module cannot report the progress with normal close.
I solved the problem by adding the LMS close part to normal close.
The progress is reported properly.
Didn't see and side effects with the LMSes we are using ILIAS and Moodle.

if (config._button._closeViaLMSFinish) {
        var scorm = require('extensions/adapt-contrib-spoor/js/scorm/wrapper');
        if (scorm) scorm.getInstance().finish();
      } else {
        var scorm = require('extensions/adapt-contrib-spoor/js/scorm/wrapper');
        if (scorm) scorm.getInstance().finish();
        top.window.close();
      }
No side effects with simple web use as well.
I think this can be safely changed in the plugin.

May be a new name of the parameter should be invented, because now the close is always with LMS Finish, but one case closes the window, the other one not.

**Comment by moloko** [comment]
Hi @dymitar I'm happy to have a look at this - although this issue is actually at the LMS level I appreciate it's not a quick process getting them to patch the problem (or even getting them to admit it IS their problem to fix!!) 

Moodle released a fix for this sometime ago though so that should be OK

**Comment by moloko** [comment]
@dymitar please see #16 - in the end I decided this didn't really need a setting, it's easier just to have it always call `LMSFinish` on close, assuming that:
- the spoor extension is installed
- the course is connected to an LMS
- `LMSFinish` hasn't already been called

**Comment by dymitar** [comment]
Perfect, this definitely fixes the problem.
With a patch I applied we re-published more than 20 learning courses and they are working as expected.
btw, I don't know what exactly moodle released as a patch, but we have 2 clients with moodle and we had to republish the courses for them. I don't know what is the exact version of their moodle.
