### ISSUE TITLE
Close button disappears

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-close#18]
Not sure if this is related to the existing issue, but the close button disappears when the Language Picker (https://github.com/adaptlearning/adapt-contrib-languagePicker) is also used.

The close button is initially is shown, but if the languages are changed using the language picker in the nav bar the close button either disappears from the nav bar or is hidden by the language picker button.

Thanks

**Comment by sarveshwar-gavhane** [comment]
@fosterc1 try this
