### ISSUE TITLE
missing styles

### ISSUE THREAD

**Issue by gorhgorh** [cgkineo/adapt-close#2]
in the hbs template you can add a style depending on the course.json "_layout" key (left or right) since no less files is provided with it, it have no effect, I added a less file for my version but i was wondering if it make sense to add it to the repo as well, If yes I'll make a PR for this, if not, feel free to close this issue.

**Comment by tomgreenfield** [comment]
This particular property was a hangover from our internal framework / theme combination. This has been removed in the refactor, thanks.
